---
title: "analysis_script"
author: "Lisa Wei"
date: '2017-03-16'
output: html_document
---

```{r setup, message=FALSE}

library(lattice)
# source("https://bioconductor.org/biocLite.R")
# biocLite("ComplexHeatmap")

library(ggplot2)
library(plyr)
library(dplyr)
library(gplots)
library(RColorBrewer)
#library(ComplexHeatmap)
#library(circlize)

load("/Volumes/Transcend/Batch_cell_corrected_data/GSE59685_batch_cell_cor.RData", verbose=TRUE) ## GSE59685_cell_cor
load("/Volumes/Transcend/Batch_cell_corrected_data/GSE59685_batch_cor.RData", verbose=TRUE) ## GSE59685_batch_cor
load("/Volumes/Transcend/Batch_cell_corrected_data/Meta_brain_cell_batch.RData", verbose=TRUE) ## meta

## add another broad region column
meta$broad_regions <- ifelse(meta$Tissue == "cerebellum", "cerebellum","cortex")
meta$tissue_color <- lapply(meta$Tissue,function(x){
  if (x == "cerebellum") {y <- "red"}
  if (x == "frontal cortex") {y <- "blue"}
  if (x == "superior temporal gyrus") {y <- "orange"}
  if (x == "entorhinal cortex") {y <- "yellow"}
  y
  })

meta$broad_colors <- lapply(meta$broad_regions,function(x){
  if (x == "cerebellum") {y <- "red"}
  if (x == "cortex") {y <- "blue"}
  y
})

## transpose data such that probe names are colnames, and rows are patient samples
transpose_GSE59685_cell_cor <- t(GSE59685_cell_cor)
## order metadata by brain region
meta_order_by_brain_regions <- meta %>% arrange(Tissue)
matches_GSE59685_cell_cor <- match(meta_order_by_brain_regions$gsm, rownames(transpose_GSE59685_cell_cor))
GSE59685_cell_cor_sorted_by_brain_regions <- t(transpose_GSE59685_cell_cor[matches_GSE59685_cell_cor,])

### overall patterns in methylation patterns across brain regions
## define color scale
jBuPuFun <- colorRampPalette(brewer.pal(n = 9, "BuPu"))


```

```{r heatmap1, fig.width=15, fig.height=15}
heatmap.2(GSE59685_cell_cor_sorted_by_brain_regions, scale="none", trace="none",margins = c(10, 10), col = jBuPuFun(256), ColSideColors = as.character(meta_order_by_brain_regions$broad_color))

legend("topright", legend = c("cerebellum", "cortex"), col = c("red", "blue"),lty= 1,lwd = 10)

```

```{r heatmap2, fig.width=15, fig.height=15, message=FALSE}
###=============================================
## repeat for bach-corrected only data
## transpose data such that probe names are colnames, and rows are patient samples
transpose_GSE59685_batch_cor <- t(GSE59685_batch_cor)
## order metadata by brain region
meta_order_by_brain_regions <- meta %>% arrange(Tissue)
matches_GSE59685_batch_cor <- match(meta_order_by_brain_regions$gsm, rownames(transpose_GSE59685_batch_cor))
GSE59685_batch_cor_sorted_by_brain_regions <- t(transpose_GSE59685_batch_cor[matches_GSE59685_batch_cor,])

### overall patterns in methylation patterns across brain regions
## define color scale
jBuPuFun <- colorRampPalette(brewer.pal(n = 9, "BuPu"))

heatmap.2(GSE59685_batch_cor_sorted_by_brain_regions, scale="none", trace="none",margins = c(10, 10), col = jBuPuFun(256), ColSideColors = as.character(meta_order_by_brain_regions$broad_color))

legend("topright", legend = c("cerebellum", "cortex"), col = c("red", "blue"), lty= 1,lwd = 10)

```